//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOAGenerator.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class bil_SettlementCutOff
    {
        public long SettlementCutOffID { get; set; }
        public System.DateTime settlement_date { get; set; }
        public int merchant_id { get; set; }
        public int InternalCompanyID { get; set; }
        public int CorporateID { get; set; }
        public int AcquirerID { get; set; }
        public int settlement_batch_id { get; set; }
        public decimal CurrentBalance { get; set; }
        public decimal Transaction_GrossAmount { get; set; }
        public decimal Transaction_MerchantMDRAmount { get; set; }
        public decimal Transaction_MerchantWHTAmount { get; set; }
        public decimal Transaction_BankMDRAmount { get; set; }
        public decimal Transaction_BankGrossAmountReceivable { get; set; }
        public decimal Transaction_BankWHTAmount { get; set; }
        public decimal Transaction_BankNetAmountReceivable { get; set; }
        public decimal Transaction_NetAmount { get; set; }
        public decimal Chargeback_GrossAmount { get; set; }
        public decimal Chargeback_MerchantMDRAmount { get; set; }
        public decimal Chargeback_MerchantWHTAmount { get; set; }
        public decimal Chargeback_BankMDRAmount { get; set; }
        public decimal Chargeback_BankGrossAmountReceivable { get; set; }
        public decimal Chargeback_BankWHTAmount { get; set; }
        public decimal Chargeback_BankNetAmountReceivable { get; set; }
        public decimal Chargeback_NetAmount { get; set; }
        public decimal Refund_GrossAmount { get; set; }
        public decimal Refund_MerchantMDRAmount { get; set; }
        public decimal Refund_MerchantWHTAmount { get; set; }
        public decimal Refund_BankMDRAmount { get; set; }
        public decimal Refund_BankGrossAmountReceivable { get; set; }
        public decimal Refund_BankWHTAmount { get; set; }
        public decimal Refund_BankNetAmountReceivable { get; set; }
        public decimal Refund_NetAmount { get; set; }
        public decimal AdjustmentAmount { get; set; }
        public decimal AmountPaid { get; set; }
        public decimal RemainingBalance { get; set; }
        public decimal Fraud_GrossAmount { get; set; }
        public decimal Fraud_MerchantMDRAmount { get; set; }
        public decimal Fraud_MerchantWHTAmount { get; set; }
        public decimal Fraud_BankMDRAmount { get; set; }
        public decimal Fraud_BankGrossAmountReceivable { get; set; }
        public decimal Fraud_BankWHTAmount { get; set; }
        public decimal Fraud_BankNetAmountReceivable { get; set; }
        public decimal Fraud_NetAmount { get; set; }
        public System.DateTime CreatedOn { get; set; }
    }
}
