//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOAGenerator.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class M3_DEVEntities : DbContext
    {
        public M3_DEVEntities()
            : base("name=M3_DEVEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<bil_SettlementCutOff> bil_SettlementCutOff { get; set; }
        public DbSet<bil_SettlementFraud> bil_SettlementFraud { get; set; }
        public DbSet<m3_merchant> m3_merchant { get; set; }
        public DbSet<m3_merchant_contact> m3_merchant_contact { get; set; }
        public DbSet<tpa_settlement_batch> tpa_settlement_batch { get; set; }
        public DbSet<tpa_settlementtransaction> tpa_settlementtransaction { get; set; }
        public DbSet<tpa_SettlementTransactionStatus> tpa_SettlementTransactionStatus { get; set; }
        public DbSet<vw_SOADailyTransaction> vw_SOADailyTransaction { get; set; }
        public DbSet<vw_SOALastDayofMonthlyFraud> vw_SOALastDayofMonthlyFraud { get; set; }
        public DbSet<vw_SOAMonthlyTransaction> vw_SOAMonthlyTransaction { get; set; }
    }
}
