//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOAGenerator.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tpa_settlementtransaction
    {
        public string reconcile_tx_id { get; set; }
        public byte transactiontype { get; set; }
        public Nullable<int> settlement_batch_id { get; set; }
        public Nullable<System.DateTime> transaction_date { get; set; }
        public Nullable<decimal> tx_amount { get; set; }
        public Nullable<int> merchant_id { get; set; }
        public Nullable<int> MDRSchemeID { get; set; }
        public Nullable<decimal> merchant_mdr_percentage { get; set; }
        public Nullable<decimal> merchant_mdr_flat { get; set; }
        public Nullable<decimal> merchant_vat_rate { get; set; }
        public Nullable<decimal> merchant_wht_rate { get; set; }
        public Nullable<decimal> merchant_mdr_minimumrate { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<decimal> bank_mdr_percentage { get; set; }
        public Nullable<decimal> bank_mdr_flat { get; set; }
        public Nullable<decimal> bank_vat_rate { get; set; }
        public Nullable<decimal> bank_wht_rate { get; set; }
        public Nullable<decimal> bank_mdr_minimumrate { get; set; }
        public Nullable<System.DateTime> tx_create_date { get; set; }
        public Nullable<decimal> override_merchant_mdr_amount { get; set; }
        public Nullable<decimal> override_merchant_mdr_percentage { get; set; }
        public Nullable<decimal> override_merchant_mdr_flat { get; set; }
        public Nullable<decimal> override_product_mdr_amount { get; set; }
        public Nullable<decimal> override_product_mdr_percentage { get; set; }
        public Nullable<decimal> override_product_mdr_flat { get; set; }
        public Nullable<int> AcquirerID { get; set; }
        public string MID { get; set; }
        public string TID { get; set; }
        public string card_pan { get; set; }
        public string account_no { get; set; }
        public string auth_code { get; set; }
        public string pos_mode { get; set; }
        public string CurrencyCode { get; set; }
        public string card_scheme { get; set; }
        public string card_scheme_class { get; set; }
        public Nullable<System.DateTime> ImportedDate { get; set; }
        public Nullable<System.DateTime> match_date { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<System.DateTime> scheduledsettlement { get; set; }
        public Nullable<decimal> computed_merchant_mdr_amount { get; set; }
        public Nullable<decimal> computed_merchant_wht_amount { get; set; }
        public Nullable<decimal> computed_pay_to_merchant_amount { get; set; }
        public Nullable<decimal> computed_bank_mdr_amount { get; set; }
        public Nullable<decimal> computed_gross_amount_receivable_from_bank { get; set; }
        public Nullable<decimal> computed_bank_wht_amount { get; set; }
        public Nullable<decimal> computed_net_amount_receivable_from_bank { get; set; }
    }
}
