//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOAGenerator.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tpa_settlement_batch
    {
        public int settlement_batch_id { get; set; }
        public System.DateTime settlement_date { get; set; }
        public Nullable<int> reconcile_tx_count { get; set; }
        public Nullable<decimal> reconcile_tx_amount { get; set; }
        public Nullable<int> credit_refund_count { get; set; }
        public Nullable<decimal> credit_refund_amount { get; set; }
        public Nullable<int> charge_back_count { get; set; }
        public Nullable<decimal> charge_back_amount { get; set; }
    }
}
