//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOAGenerator.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_SOAMonthlyTransaction
    {
        public Nullable<int> syear { get; set; }
        public Nullable<int> smonth { get; set; }
        public int merchant_id { get; set; }
        public decimal monthCurrentBalance { get; set; }
        public Nullable<decimal> totalTransactionAmount { get; set; }
        public Nullable<decimal> totalChargebackAmount { get; set; }
        public Nullable<decimal> totalRefundAmount { get; set; }
        public Nullable<decimal> totalAdjustmentAmount { get; set; }
        public Nullable<decimal> totalAmountPaid { get; set; }
        public decimal monthRemainingBalance { get; set; }
    }
}
