//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateSOADLL.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class M3_PROEntities : DbContext
    {
        public M3_PROEntities()
            : base("name=M3_PROEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<vw_SOADailyTransaction> vw_SOADailyTransaction { get; set; }
        public DbSet<bil_SettlementCutOff> bil_SettlementCutOff { get; set; }
        public DbSet<m3_EmailSender> m3_EmailSender { get; set; }
        public DbSet<m3_EmailAttachment> m3_EmailAttachment { get; set; }
        public DbSet<m3_EmailRecipient> m3_EmailRecipient { get; set; }
        public DbSet<vw_MerchantFirstContact> vw_MerchantFirstContact { get; set; }
        public DbSet<m3_merchant> m3_merchant { get; set; }
        public DbSet<m3_merchant_contact> m3_merchant_contact { get; set; }
    
        [EdmFunction("M3_PROEntities", "fn_SOADailyHeaders")]
        public virtual IQueryable<fn_SOADailyHeaders_Result> fn_SOADailyHeaders(Nullable<System.DateTime> sOADated)
        {
            var sOADatedParameter = sOADated.HasValue ?
                new ObjectParameter("SOADated", sOADated) :
                new ObjectParameter("SOADated", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_SOADailyHeaders_Result>("[M3_PROEntities].[fn_SOADailyHeaders](@SOADated)", sOADatedParameter);
        }
    
        [EdmFunction("M3_PROEntities", "fn_SOADailyWithheldTransactions")]
        public virtual IQueryable<fn_SOADailyWithheldTransactions_Result> fn_SOADailyWithheldTransactions(Nullable<System.DateTime> sOADated)
        {
            var sOADatedParameter = sOADated.HasValue ?
                new ObjectParameter("SOADated", sOADated) :
                new ObjectParameter("SOADated", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_SOADailyWithheldTransactions_Result>("[M3_PROEntities].[fn_SOADailyWithheldTransactions](@SOADated)", sOADatedParameter);
        }
    }
}
