//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateSOADLL.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_SOADailyTransaction
    {
        public Nullable<System.DateTime> statementdate { get; set; }
        public Nullable<int> merchant_id { get; set; }
        public Nullable<System.DateTime> transactiondate { get; set; }
        public string transactionid { get; set; }
        public string transactioncode { get; set; }
        public string transactiontype { get; set; }
        public Nullable<decimal> transactionamount { get; set; }
        public Nullable<decimal> transactionMDR { get; set; }
        public Nullable<decimal> transactionWHT { get; set; }
        public Nullable<decimal> netamount { get; set; }
        public string country { get; set; }
        public string productname { get; set; }
    }
}
